### ISSUE TITLE
add htpasswd function for clusterbom to deploy yaml 

### ISSUE THREAD

**Issue by gowrisankar22** [gardener/potter-hub#12]
**What would you like to be added**:

The htpasswd function takes a username and password and generates a bcrypt hash of the password. The result can be used for basic authentication on Prometheus, alert manager,thanos etc.

**Why is this needed**:
We are using potter to deploy helm/plain yaml based deployments etc. Right now we are doing some manual work to generate htpasswd for Prometheus, alert manager,thanos, etc to have basic auth via plain yamls. it would be great if you can enable this  function via cluster bomb

```
action create_manifest for deployment k8s-monitoring failed. action output:
 could not execute apphub template, cause: template: clusterbom.yml:75:3: executing "clusterbom.yml" at <generateTemplate $basicAuth .>: error calling generateTemplate: template: basic-auth.yml:3: function "htpasswd" not defined
```

helm already support htpasswd function. Reference from helm:  https://helm.sh/docs/chart_template_guide/function_list/#htpasswd

**Comment by In-Ko** [comment]
Thanks @gowrisankar22 for creating this enhancement request. We will look into this and get back to you.

**Comment by achimweigel** [comment]
I'm not sure if I understand your use case the right way. Could you perhaps add the clusterbom you want to deploy? htpasswd used in a template of a helm chart should be already supported.

**Comment by gowrisankar22** [comment]
@achimweigel  Yes, helm supports it but if I want to deploy plain yaml via clusterbom with htpasswd it won't work.
Example: I have a k8s secret which I want to deploy via clusterbom but it requires htpasswd which comes some values.yml(not via helm). This is what is not working.

```yaml
apiVersion: v1
kind: Secret
metadata:  
    name: basicauth  
type: Opaque
data:  
  REGISTRY_HTPASSWD: {{ htpasswd .Values.registry.credentials.username .Values.registry.credentials.password  | b64enc | quote }} 


clusterbom section:
--------
- id: basicauth
    configType: kapp
    typeSpecificData:
      fetch:
        - inline:
            paths:
              basicauth.yml: |
{{ generateTemplate $basicAuth . | indent 18 }}
      template:
        - ytt: {}
      deploy:
        - kapp:
            intoNs: xxxx

```
